name: Build with BuildKit

on:
  push:
    branches: '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Extract tag name
        env:
          REF_PATH: ${{ github.ref }}
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${REF_PATH#refs/*/})"
        id: extract_ref
      -
        name: Build Docker image and push to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          export HISTFILE=
          echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
          docker buildx build --push --platform linux/arm/v7,linux/amd64 --tag ccfactory/${{ github.repository }}:${{ steps.extract_ref.outputs.ref }} .
          docker logout
