name: Publish on push
# branch name in Git becomes tag name in Docker Hub
# subseqent pushes to branch overwrites previous Docker tag

on:
  push:
    branches: '*'

jobs:

  build:

    runs-on: ${{ matrix.label }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        label: [ubuntu-latest]
        experimental: [false]
        include:
          - label: ARM
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        export HISTFILE=
        echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
        docker build . --file Dockerfile --tag ${{ github.repository }}
        docker logout
    - name: Extract tag name
      env:
        REF_PATH: ${{ github.ref }}
      shell: bash
      run: echo "##[set-output name=ref;]$(echo ${REF_PATH#refs/*/})"
      id: extract_ref
    - name: Push to Docker Hub
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        # dunno if useful, but why not to erase it?
        export HISTFILE=
        echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
        export REPO=${{ github.repository }}
        docker tag ${{ github.repository }} ccfactory/${REPO##*/}:${{ steps.extract_ref.outputs.ref }}
        docker push ccfactory/${REPO##*/}:${{ steps.extract_ref.outputs.ref }}
        docker logout
